title: Label a spectrogram
type: community
group: Computer Vision
order: 3
image: /static/templates/spectrogram.jpg
details: <h1>Label a spectrogram/h1>
config: |
  
  
  <View>
     <Labels name="labels" toName="spec">
      <Label value="Mopsfledermaus" />
      <Label value="MÃ¼ckenfledermaus" />
    </Labels>
 
    <Spectrogram name="spec" value="$spec" zoom="true" hotkey="ctrl+enter" />
  
  </View>
